version: "3"

networks:
  app_proxy:
  #  name: ${COMPOSE_NET}
  db_net:
  

volumes:
  caddy_data: {}
  app_data:
    name: ${COMPOSE_VOLUME}
  db_data:

services:
  caddy:
    container_name: marketplace_proxy
    image: lucaslorentz/caddy-docker-proxy:${CADDY_PROXY_VERSION?err}
    networks:
      - app_proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      labels:
        caddy.email: ${LETSENCRYPT_EMAIL?err}
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any # unless-stopped # use any for docker-compose version < 2
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

  marketplace-app:
    container_name: ${COMPOSE_HOSTNAME}
    build:
      context: ./app/.
      dockerfile: Dockerfile.${SOL_NET}
      args:
        #NODE_ENV: ${NODE_ENV}
        NODE_VERSION: ${NODE_VERSION}
        NEXT_BASE_PATH: ${NEXT_BASE_PATH}
        NEXT_PUBLIC_SOLANA_NETWORK: ${NEXT_PUBLIC_SOLANA_NETWORK}
        NEXT_PUBLIC_SOLANA_RPC_HOST: ${NEXT_PUBLIC_SOLANA_RPC_HOST}
        NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
        NEXT_PUBLIC_STORE_ADDRESS: ${NEXT_PUBLIC_STORE_ADDRESS}
        NEXT_ENABLE_NFT_PACKS: ${NEXT_ENABLE_NFT_PACKS}
        NEXT_SPL_TOKEN_MINTS: ${NEXT_SPL_TOKEN_MINTS}
        NEXT_CG_SPL_TOKEN_IDS: ${NEXT_CG_SPL_TOKEN_IDS}
    user: "node:node"
    networks:
      - app_proxy
    ports:
      - "${COMPOSE_PORT}:${NEXT_PORT}"
    volumes:
      - "app_data:/app:rw"
    command: ${COMPOSE_COMMAND}
    working_dir: /app
    env_file:
      - ${ENV_FILE}
    labels:
      caddy: ${WEBSITE_HOSTNAME?err}
      caddy.reverse_proxy: "{{upstreams http ${NEXT_PORT}}}"
       # caddy.tls: "${CADDY_TLS}"
      caddy.tls.ca: "https://acme-staging-v02.api.letsencrypt.org/directory" # "https://acme-v02.api.letsencrypt.org/directory"
      caddy.@ws.0_header: Connection *Upgrade*
      caddy.@ws.1_header: Upgrade websocket
    deploy:
      replicas: 1
      restart_policy:
        condition: any      

  backend-app:
    container_name: marketplace_backend
    build: 
      context: ./backend/.
      dockerfile: Dockerfile.${SOL_NET}
    stdin_open: true
    tty: true
    networks:
      - app_proxy
      - db_net
    volumes:
      - "./backend/seed/data:/src/data"
    # command: "node ./seed/seeder.js"
    environment:
      # - MONGODB_CONNSTRING="mongodb://${MONGODB_USER?err}:${MONGODB_PASSWORD?err}@marketplace_db:${MONGODB_DOCKER_PORT?err}/${MONGODB_DATABASE?err}"
      - MONGODB_CONNSTRING="mongodb://${MONGODB_USER?err}:${MONGODB_PASSWORD?err}@marketplace_db"
    depends_on:
      - mongodatabase
    labels:
      caddy: ${WEBSITE_HOSTNAME?err}
      caddy.route: "/api/*"
      caddy.route.0_uri: "strip_prefix /api"
      caddy.route.1_rewrite: "* /api{path}"
      caddy.route.2_reverse_proxy: "{{upstreams http 8080}}"
      caddy.tls.ca: "https://acme-staging-v02.api.letsencrypt.org/directory" # "https://acme-v02.api.letsencrypt.org/directory"
    deploy:
      replicas: 1
      restart_policy:
        condition: any

  mongodatabase:
    container_name: marketplace_db
    image: mongo:5.0.2  
    networks:
      - db_net
    volumes:
      - db_data:/data/db
    environment:
      # Refs: https://hub.docker.com/_/mongo
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USER?err}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD?err}
      # MongoDB is fundamentally designed for "create on first use", so if you do not insert data with your JavaScript files, then no database is created.
      # - MONGO_INITDB_DATABASE=${MONGODB_DATABASE?err}
    deploy:
      replicas: 1
      restart_policy:
        condition: any    