version: "3"

networks:
  app_proxy:
    name: ${COMPOSE_NET}

volumes:
  app_data:
    name: ${COMPOSE_VOLUME}
  caddy_data: {}

services:
  caddy:
    container_name: marketplace_proxy
    image: lucaslorentz/caddy-docker-proxy:${CADDY_PROXY_VERSION?err}
    ports:
      - 80:80
      - 443:443
    networks:
      - app_proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data
    deploy:
      labels:
        caddy.email: ${LETSENCRYPT_EMAIL?err}
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      restart_policy:
        condition: any # unless-stopped # use any for docker-compose version < 2
      resources:
        reservations:
          cpus: "0.1"
          memory: 200M

  marketplace-app:
    build:
      context: ./app/.
      dockerfile: Dockerfile.${SOL_NET}
      args:
        #NODE_ENV: ${NODE_ENV}
        NODE_VERSION: ${NODE_VERSION}
        NEXT_BASE_PATH: ${NEXT_BASE_PATH}
        NEXT_PUBLIC_SOLANA_NETWORK: ${NEXT_PUBLIC_SOLANA_NETWORK}
        NEXT_PUBLIC_SOLANA_RPC_HOST: ${NEXT_PUBLIC_SOLANA_RPC_HOST}
        NEXT_PUBLIC_GOOGLE_ANALYTICS_ID: ${NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}
        NEXT_PUBLIC_STORE_ADDRESS: ${NEXT_PUBLIC_STORE_ADDRESS}
        NEXT_ENABLE_NFT_PACKS: ${NEXT_ENABLE_NFT_PACKS}
        NEXT_SPL_TOKEN_MINTS: ${NEXT_SPL_TOKEN_MINTS}
        NEXT_CG_SPL_TOKEN_IDS: ${NEXT_CG_SPL_TOKEN_IDS}

    container_name: ${COMPOSE_HOSTNAME}
    user: "node:node"
    restart: unless-stopped
    networks:
      - app_proxy
    ports:
      - "${COMPOSE_PORT}:${NEXT_PORT}"
    volumes:
      - "app_data:/app:rw"
    command: ${COMPOSE_COMMAND}
    working_dir: /app
    env_file:
      - ${ENV_FILE}
    labels:
      caddy: ${WEBSITE_HOSTNAME?err}
      caddy.reverse_proxy: "{{upstreams http ${NEXT_PORT}}}"
       # caddy.tls: "${CADDY_TLS}"
      caddy.tls.ca: "https://acme-v02.api.letsencrypt.org/directory" #"https://acme-staging-v02.api.letsencrypt.org/directory"
      caddy.@ws.0_header: Connection *Upgrade*
      caddy.@ws.1_header: Upgrade websocket

